sudo: required

language: generic

services:
  - docker

before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t sconaway/docker-arduino-cli .
  - docker push sconaway/docker-arduino-cli
