sudo: required

language: minimal

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull ubuntu

script:
  - docker build -t sconaway/docker-arduino-cli ./Dockerfile
  - docker build ./Dockerfile-test

after_success:
  - docker push sconaway/docker-arduino-cli
