#! /usr/bin/env bash

set -ex

apt update
apt install -y \
    curl

curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

arduino-cli version

apt purge -y \
    curl

apt autoremove -y

apt clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
