#! /usr/bin/env bash

set -ex

apt update
apt install -y \
  wget
  
CLI_URL="https://downloads.arduino.cc/arduino-cli/arduino-cli-latest-linux64.tar.bz2"

wget -qO- $CLI_URL | tar xvj

ln arduino-cli-$LATEST_VERSION-linux64 /usr/local/bin/arduino-cli

arduino-cli version

apt purge \
  wget

apt autoremove -y 

apt clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
